import { GalleryItem, GalleryCategory } from "./types";

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  { id: "all", label: "All" },
  { id: "core", label: "Core" },
  { id: "brand", label: "Brand" },
  { id: "partners", label: "Partners" },
  { id: "circle", label: "Circle" },
  { id: "objects", label: "Objects" },
  { id: "artist", label: "Artist" },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "item-01",
    title: "Image Name",
    imageSrc: "/temp/1.png",
    // imageWidth: 321,
    // imageHeight: 222,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "core",
  },
  {
    id: "item-02",
    title: "Image Name",
    imageSrc: "/temp/2.png",
    // imageWidth: 321,
    // imageHeight: 131,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "brand",
  },
  {
    id: "item-03",
    title: "Image Name",
    imageSrc: "/temp/3.png",
    // imageWidth: 321,
    // imageHeight: 353,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "partners",
  },
  {
    id: "item-04",
    title: "Image Name",
    imageSrc: "/temp/4.png",
    // imageWidth: 321,
    // imageHeight: 179,
    // gradientFrom: "#FFDDBF",
    // gradientTo: "#998573",
    category: "circle",
  },
  {
    id: "item-05",
    title: "Image Name",
    imageSrc: "/temp/5.png",
    // imageWidth: 321,
    // imageHeight: 469,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "objects",
  },
  {
    id: "item-06",
    title: "Image Name",
    imageSrc: "/temp/6.png",
    // imageWidth: 320,
    // imageHeight: 317,
    // gradientFrom: "#FFDDBF",
    // gradientTo: "#998573",
    category: "artist",
  },
  {
    id: "item-07",
    title: "Image Name",
    imageSrc: "/temp/7.png",
    // imageWidth: 320,
    // imageHeight: 179,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "core",
  },
  {
    id: "item-08",
    title: "Image Name",
    imageSrc: "/temp/8.png",
    // imageWidth: 320,
    // imageHeight: 315,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "brand",
  },
  {
    id: "item-09",
    title: "Image Name",
    imageSrc: "/temp/9.png",
    // imageWidth: 320,
    // imageHeight: 180,
    // gradientFrom: "#FFDDBF",
    // gradientTo: "#998573",
    category: "partners",
  },
  {
    id: "item-10",
    title: "Image Name",
    imageSrc: "/temp/10.png",
    // imageWidth: 320,
    // imageHeight: 179,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "circle",
  },
  {
    id: "item-11",
    title: "Image Name",
    imageSrc: "/temp/1.png",
    // imageWidth: 320,
    // imageHeight: 103,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "objects",
  },
  {
    id: "item-12",
    title: "Image Name",
    imageSrc: "/temp/2.png",
    // imageWidth: 320,
    // imageHeight: 251,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "artist",
  },
  {
    id: "item-13",
    title: "Image Name",
    imageSrc: "/temp/3.png",
    // imageWidth: 320,
    // imageHeight: 246,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "core",
  },
  {
    id: "item-14",
    title: "Image Name",
    imageSrc: "/temp/4.png",
    // imageWidth: 320,
    // imageHeight: 351,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "brand",
  },
  {
    id: "item-15",
    title: "Image Name",
    imageSrc: "/temp/5.png",
    // imageWidth: 320,
    // imageHeight: 397,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "partners",
  },
  {
    id: "item-16",
    title: "Image Name",
    imageSrc: "/temp/6.png",
    // imageWidth: 320,
    // imageHeight: 129,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "circle",
  },
  {
    id: "item-17",
    title: "Image Name",
    imageSrc: "/temp/7.png",
    // imageWidth: 321,
    // imageHeight: 317,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "objects",
  },
  {
    id: "item-18",
    title: "Image Name",
    imageSrc: "/temp/8.png",
    // imageWidth: 321,
    // imageHeight: 355,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "artist",
  },
  {
    id: "item-19",
    title: "Image Name",
    imageSrc: "/temp/9.png",
    // imageWidth: 321,
    // imageHeight: 193,
    // gradientFrom: "#CEEBFF",
    // gradientTo: "#7C8D99",
    category: "core",
  },
  {
    id: "item-20",
    title: "Image Name",
    imageSrc: "/temp/10.png",
    // imageWidth: 321,
    // imageHeight: 70,
    // gradientFrom: "#E7DDFF",
    // gradientTo: "#8B8499",
    category: "brand",
  },
  {
    id: "item-21",
    title: "Image Name",
    imageSrc: "/temp/1.png",
    // imageWidth: 321,
    // imageHeight: 179,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "partners",
  },
  {
    id: "item-22",
    title: "Image Name",
    imageSrc: "/temp/2.png",
    // imageWidth: 321,
    // imageHeight: 159,
    // gradientFrom: "#FFE2E2",
    // gradientTo: "#998787",
    category: "partners",
  }
];
