import { GalleryItem, GalleryCategory } from "./types";

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  { id: "all", label: "All" },
  { id: "core", label: "Core" },
  { id: "brand", label: "Brand" },
  { id: "partners", label: "Partners" },
  { id: "circle", label: "Circle" },
  { id: "objects", label: "Objects" },
  { id: "artist", label: "Artist" },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "item-01",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x222",
    imageWidth: 321,
    imageHeight: 222,
    gradientFrom: "#FFE2E2",
    gradientTo: "#998787",
    category: "core",
  },
  {
    id: "item-02",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x131",
    imageWidth: 321,
    imageHeight: 131,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "brand",
  },
  {
    id: "item-03",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x353",
    imageWidth: 321,
    imageHeight: 353,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "partners",
  },
  {
    id: "item-04",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x179",
    imageWidth: 321,
    imageHeight: 179,
    gradientFrom: "#FFDDBF",
    gradientTo: "#998573",
    category: "circle",
  },
  {
    id: "item-05",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x469",
    imageWidth: 321,
    imageHeight: 469,
    gradientFrom: "#FFE2E2",
    gradientTo: "#998787",
    category: "objects",
  },
  {
    id: "item-06",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x317",
    imageWidth: 320,
    imageHeight: 317,
    gradientFrom: "#FFDDBF",
    gradientTo: "#998573",
    category: "artist",
  },
  {
    id: "item-07",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x179",
    imageWidth: 320,
    imageHeight: 179,
    gradientFrom: "#FFE2E2",
    gradientTo: "#998787",
    category: "core",
  },
  {
    id: "item-08",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x315",
    imageWidth: 320,
    imageHeight: 315,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "brand",
  },
  {
    id: "item-09",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x180",
    imageWidth: 320,
    imageHeight: 180,
    gradientFrom: "#FFDDBF",
    gradientTo: "#998573",
    category: "partners",
  },
  {
    id: "item-10",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x179",
    imageWidth: 320,
    imageHeight: 179,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "circle",
  },
  {
    id: "item-11",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x103",
    imageWidth: 320,
    imageHeight: 103,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "objects",
  },
  {
    id: "item-12",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x251",
    imageWidth: 320,
    imageHeight: 251,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "artist",
  },
  {
    id: "item-13",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x246",
    imageWidth: 320,
    imageHeight: 246,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "core",
  },
  {
    id: "item-14",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x351",
    imageWidth: 320,
    imageHeight: 351,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "brand",
  },
  {
    id: "item-15",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x397",
    imageWidth: 320,
    imageHeight: 397,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "partners",
  },
  {
    id: "item-16",
    title: "Image Name",
    imageSrc: "https://placehold.co/320x129",
    imageWidth: 320,
    imageHeight: 129,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "circle",
  },
  {
    id: "item-17",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x317",
    imageWidth: 321,
    imageHeight: 317,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "objects",
  },
  {
    id: "item-18",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x355",
    imageWidth: 321,
    imageHeight: 355,
    gradientFrom: "#FFE2E2",
    gradientTo: "#998787",
    category: "artist",
  },
  {
    id: "item-19",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x193",
    imageWidth: 321,
    imageHeight: 193,
    gradientFrom: "#CEEBFF",
    gradientTo: "#7C8D99",
    category: "core",
  },
  {
    id: "item-20",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x70",
    imageWidth: 321,
    imageHeight: 70,
    gradientFrom: "#E7DDFF",
    gradientTo: "#8B8499",
    category: "brand",
  },
  {
    id: "item-21",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x179",
    imageWidth: 321,
    imageHeight: 179,
    gradientFrom: "#FFE2E2",
    gradientTo: "#998787",
    category: "partners",
  },
  {
    id: "item-22",
    title: "Image Name",
    imageSrc: "https://placehold.co/321x159",
    imageWidth: 321,
    imageHeight: 159,
    gradientFrom: "#FFDDBF",
    gradientTo: "#998573",
    category: "circle",
  },
];
